ALTER TABLE "WorkOrder" ADD COLUMN "archived" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SaleOrder" ADD COLUMN "archived" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ServiceRequest" ADD COLUMN "archived" BOOLEAN NOT NULL DEFAULT false;