CREATE TYPE "Role_new" AS ENUM (
  'ADMIN', 'MANAGER', 'REQUESTER',
  'MAINTENANCE_LEADER', 'MAINTENANCE_TECHNICIAN',
  'TNC_LEADER', 'TNC_ENGINEER',
  'SALES_LEADER', 'SALES_ENGINEER',
  'QC_LEADER', 'QC_ENGINEER',
  'SHOP_DRAWING_LEADER', 'SHOP_DRAWING_ENGINEER',
  'ANA_LEADER', 'ANA_ENGINEER'
);

ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role_new" USING (
  CASE "role"::text
    WHEN 'TECHNICIAN' THEN 'MAINTENANCE_TECHNICIAN'
    WHEN 'SALES' THEN 'SALES_ENGINEER'
    WHEN 'ENGINEERING' THEN 'SHOP_DRAWING_ENGINEER'
    WHEN 'AA' THEN 'ANA_ENGINEER'
    WHEN 'MAINTENANCE_SUP' THEN 'MAINTENANCE_LEADER'
    ELSE "role"::text
  END
)::"Role_new";

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'REQUESTER';

DROP TYPE "Role";
ALTER TYPE "Role_new" RENAME TO "Role";

UPDATE "Team" SET name = 'ANA' WHERE name = 'AA';